# -*- coding: utf-8 -*-
"""Convolutional Neural Network-Fashion MNIST Project-Model Control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RycGs_FS0fzxHMLEP4ZoQplDa_kpvsZp
"""

#Burada eğitiiğimiz fashion mnist modelini
#bağımsız projede deneyrek öğrenme başarısını kontrol edelim

from google.colab import files
uploaded = files.upload()  # Bilgisayarından dosyayı seç

#Gerekli Kütüphaneleri Eklenmesi

from tensorflow.keras.models import load_model
from tensorflow.keras.datasets import fashion_mnist

import numpy as np

import matplotlib.pyplot as plt

from tensorflow.keras.models import load_model

model = load_model("fashion_mnist_modeli.h5")

#Test Verisi Yükleme ve Önişleme

(_,_),(x_test, y_test) = fashion_mnist.load_data()
#test verisi bizim için yeterli

x_test=x_test/255.0
#veriyi normalize etme

x_test = x_test.reshape(-1,28,28,1)
#cnn modeline 4 parametre gönderildi

#Etiket Tanımlama

etiket_isimleri=[
    "T-shirt/top","Pantolon","Kazak","Elbise","Palto",
    "Sandalet","Gömlek","Spor Ayakkabı","Çanta","Bot"
]

#Tahmin ve Görselleştirme

#Test setinden rastgele örnek seçip deneyelim

ornek_index=87#seçilen görselin indexi
ornek_gorsel= x_test[ornek_index]#görselin bulunması veri setinden
ornek_label = y_test[ornek_index]#görselin etiketinin bulunması


tahmin = model.predict(np.expand_dims(ornek_gorsel,axis=0))
#modelin tahminin alınması
tahmin_edilen = np.argmax(tahmin)

print(f"Gerçek etiket: {etiket_isimleri[ornek_label]}")
#gerçek etiketin yazılması
print(f"Tahmin edilen: {etiket_isimleri[tahmin_edilen]}")
#model tahminin yazılması

#Görselin çizilmesi

plt.imshow(ornek_gorsel.reshape(28,28), cmap="gray")
plt.title(f"Tahmin: {etiket_isimleri[tahmin_edilen]}-Gerçek: {etiket_isimleri[ornek_label]}")
plt.axis("off")
plt.show()