# -*- coding: utf-8 -*-
"""Convolutional Neural Network-CIFAR-10 Project-Model Control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXK_DaV-S0fPMOwRvHx28kyBWNP8YwDH
"""

#Burada ise projede eğittiğimiz modeli test edeceğiz
from google.colab import files

# Bilgisayarından .h5 modelini yükle
uploaded = files.upload()  # "cifar10_modeli.h5" dosyasını seç

#Gerekli kütüphaneleri Ekleme

from tensorflow.keras.models import load_model
from tensorflow.keras.datasets import cifar10
import numpy as np
import matplotlib.pyplot as plt

#Modeli Yükleme

model=load_model("cifar-10_modeli.h5")
print("Model başarıyla yüklendi")

#eğittiğimiz ve import ettiğimiz modeli dosyadan yükleme

#Test Verisi Hazırlama

(_,_),(x_test, y_test)=cifar10.load_data()
#eğitim verisine gerek olmadığına göre test verisi işimizi görür

x_test=x_test/255.0 #normalize etme

#Sınıf Etiketleri Tanımlama

etiket_isimleri = [
    "Uçak","Araba","Kuş","Kedi","Geyik","Köpek","Kurbağa","At","Gemi","Kamyon"
]

#Tahmin ve Görselleştirme

ornek_index=204# rastgele bir veri indexi seçilmesi

ornek_gorsel = x_test[ornek_index]# indexten görselin alınması

ornek_label= y_test[ornek_index][0]#seçilen görselin etikentinin alınması

tahmin= model.predict(np.expand_dims(ornek_gorsel,axis=0))
#modele görseli verip tahminini alma

tahmin_edilen= np.argmax(tahmin)


print(f"Gerçek Etiket: {etiket_isimleri[ornek_label]}")
print(f"Tahmin Edilen: {etiket_isimleri[tahmin_edilen]}")
#sonuçları yazıdmra

plt.imshow(ornek_gorsel)
plt.title(f"Tahmin: {etiket_isimleri[tahmin_edilen]}-Gerçek: {etiket_isimleri[ornek_label]}")
plt.axis("off")
plt.show()