# -*- coding: utf-8 -*-
"""Convolutional Neural Network-MNIST Project Model Control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsfVDNGrOaKSYMcBAlg6Dm26sGKp3oGH
"""

#Burada ilk projede eğittimğimiz cnn modelini yükleyerek test edelim

from google.colab import files
uploaded = files.upload()  # el_yazisi_modeli.h5 dosyasını yükle

from tensorflow.keras.models import load_model
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

#Daha Önce Eğittiğimiz Modeli Test Etme

model = load_model("el_yazisi_modeli.h5")

#Test Verisini Yükleme ve Hazırlama

(_,_),(x_test, y_test)=mnist.load_data()
#mnist veri setini yükleme

x_test= x_test/255.0 # normalize etme
x_test = x_test.reshape(-1,28,28,1) #uygun şekle getirme

#Tahmin Yapma


ornek_index=456 #veri setinden ratgele görsel indexi seçimi
ornek_gorsel = x_test[ornek_index]# o indexteki görseli alam
ornek_label= y_test[ornek_index]# seçilen görselin etiketine  etiket atanması

tahmin = model.predict(np.expand_dims(ornek_gorsel, axis=0))
tahmin_edilen=np.argmax = np.argmax(tahmin)

#modelin yaptığı tahminleri alma

print(f"Gerçek etiket : {ornek_label}")
print(f"Tahmin edilen etiket: {tahmin_edilen}")

plt.imshow(ornek_gorsel.reshape(28,28), cmap="gray")
plt.title(f"Tahmin: {tahmin_edilen}-Gerçek: {ornek_label}")
plt.axis("off")
plt.show()